# Nezumaid Bot Configuration

# Issue関連の設定
issues:
  # 自動ラベル設定
  labels:
    bug: ['バグ', 'エラー', '不具合', 'bug', 'error']
    enhancement: ['機能追加', '改善', '要望', 'feature', 'enhancement']
    documentation: ['ドキュメント', 'docs', 'documentation']
    help-wanted: ['help wanted', '協力募集']
    good-first-issue: ['good first issue', '初心者向け']

  # 優先度ラベル
  priority:
    high: ['urgent', '緊急', 'critical', '重要']
    medium: ['normal', '通常']
    low: ['low', '低']

  # 自動応答メッセージ
  greeting: |
    issueの作成ありがとうございます！

    内容を確認させていただきます。追加の情報が必要な場合は、お知らせいたしますので、よろしくお願いいたします。

    また、以下の点もご確認ください：
    - [コントリビューションガイド](CONTRIBUTING.md)
    - [既存のissue](https://github.com/nezumi0627/subnect-plus/issues)

# PR関連の設定
pull_requests:
  # 自動ラベル設定
  labels:
    needs-review: ['レビュー待ち', 'review required']
    work-in-progress: ['WIP', '作業中']
    size:
      xs: ['size/XS']
      s: ['size/S']
      m: ['size/M']
      l: ['size/L']

  # レビュー担当者の自動割り当て
  reviewers:
    default:
      - nezumi0627
    docs:
      - nezumi0627
    tests:
      - nezumi0627

  # PRテンプレート
  template: |
    ## 変更内容
    変更の概要を記載してください。

    ## 関連するIssue
    関連するissueがある場合は、リンクを記載してください。
    例: Closes #123

    ## 変更の種類
    - [ ] バグ修正
    - [ ] 新機能追加
    - [ ] 既存機能の改善
    - [ ] ドキュメントの更新
    - [ ] テストの追加/更新
    - [ ] その他

    ## チェックリスト
    - [ ] テストを追加/更新しました
    - [ ] ドキュメントを更新しました
    - [ ] コードレビューの準備ができています
    - [ ] CIチェックがパスしています

    ## スクリーンショット（必要な場合）

    ## 補足情報

# Discussion関連の設定
discussions:
  # カテゴリー別の自動応答
  categories:
    Q&A: |
      ご質問ありがとうございます！

      できるだけ早く回答いたしますので、しばらくお待ちください。
      追加の情報が必要な場合は、お知らせいたします。

      また、以下の点もご確認ください：
      - [ドキュメント](docs/)
      - [既存のQ&A](discussions/categories/q-a)
      - [トラブルシューティングガイド](docs/troubleshooting.md)

    Ideas: |
      素晴らしいアイデアをありがとうございます！

      プロジェクトの改善に向けて、以下の点を検討させていただきます：
      - 実現可能性
      - 優先度
      - 実装方法

      コミュニティからのフィードバックもお待ちしております。

    Show and tell: |
      素晴らしい成果物の共有ありがとうございます！

      コミュニティの皆様の創造性に感謝いたします。
      他のメンバーからのフィードバックもお待ちしております。

    General: |
      discussionの作成ありがとうございます！

      コミュニティでの活発な議論を歓迎いたします。
      建設的な意見交換をお願いいたします。

# レビュー関連の設定
reviews:
  # レビューコメントのテンプレート
  templates:
    request_changes: |
      レビューコメントが追加されました。

      修正が完了しましたら、以下の手順で対応をお願いします：
      1. レビューコメントの内容を確認
      2. 必要な修正を実施
      3. コミットとプッシュ
      4. レビューコメントに返信

      ご不明な点がありましたら、お気軽にコメントでお知らせください。

    approve: |
      PRが承認されました！

      マージの準備が整いました。以下の点を最終確認してください：
      - [ ] コンフリクトがないこと
      - [ ] CIチェックがパスしていること
      - [ ] 最新のmainブランチの変更を取り込んでいること
